# Generated by Django 2.2.1 on 2019-06-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waypoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('photo', models.TextField()),
                ('waypoints', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waypoints.Waypoint')),
            ],
        ),
    ]
