# Generated by Django 2.2.1 on 2019-06-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='waypoints',
        ),
    ]
