# Generated by Django 2.2.1 on 2019-06-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_waypoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='waypoints',
            new_name='waypoint_id',
        ),
    ]
