# Generated by Django 2.2.1 on 2019-06-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190625_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='waypoint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='waypoints.Waypoint'),
        ),
    ]
