# Generated by Django 2.2.1 on 2019-06-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0002_auto_20190622_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waypoints',
            new_name='Waypoint',
        ),
    ]
