# Generated by Django 2.2.1 on 2019-06-22 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0003_auto_20190622_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='photo',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='state',
            field=models.TextField(blank=True, default=''),
        ),
    ]
