# Generated by Django 2.2.1 on 2019-06-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0006_auto_20190628_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='waypoint',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='coordinate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waypoints.Coordinate'),
        ),
    ]
