# Generated by Django 2.2.1 on 2019-06-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_books', '0002_guestbook_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='location',
            new_name='waypoint_id',
        ),
    ]
